apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crddirs.crdtest.example.com
spec:
  group: crdtest.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cronSpec:
                type: string
              image:
                type: string
              replicas:
                type: integer
  scope: Namespaced
  names:
    plural: crddirs
    singular: crddir
    kind: CrdDir
    shortNames:
    - t
